spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: kangjiwon
  password:
  driver-class-name: org.postgresql.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
  redis:
    host: localhost
    port: 6379

jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000